### ISSUE TITLE
View total cost of products in cart

### ISSUE THREAD

**Issue by vidishaholsambre** [CSCI-GA-2820-SP24-001/shopcarts#11]
**As a** user
**I need** to view the total cost of all the products in my cart   
**So that** I can confidently move forward with making the purchase 
   
 ### Details and Assumptions
 * User should see the total dollar amount of items in the cart
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that a user has added products to the cart
 When user views all the products in the cart
 Then user should see the total dollar amount of all products in the cart
```

**Comment by whykay-01** [comment]
put this into the icebox

**Comment by whykay-01** [comment]
Closing because it is duplicating the Issue #12, which is already in the sprint backlog
