### ISSUE TITLE
Get a single item in the shopcart

### ISSUE THREAD

**Issue by alvaroperezc** [CSCI-GA-2820-SP24-001/shopcarts#16]
**As a** user/developer
**I need** to get a single item in a given shopcart 
**So that** I can observe the item details
   
 ### Details and Assumptions
 * Would be within a given shopcart id
 * GET     /shopcarts/{id}/items/{id} <- get a single item in the shopcart
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that I input the item information for a given shopcart
 When command is given
 Then the information for the item is displayed
```

**Comment by alvaroperezc** [comment]
Still a little confused what the point of this GET is.
Need to consult with @jjrofrano

**Comment by jjrofrano** [comment]
Hi @alvaroperezc , Perhaps a use case would help illustrate: Let's say you want to update the quantity of an item in the shopcart. First you would call `GET` on the item to return that single item by its `id`. Then you would update the quantity and call `PUT` on that item to update the record in the database (and thus the item in the shopcart) If you didn't have `GET`, how would you know what the current quantity value is for that shopcart item? `GET` is like a `SELECT` statement for a database (and in fact that's what it's doing under the covers). It returns a single record. Does that help?

**Comment by alvaroperezc** [comment]
Got it, thanks!
