### ISSUE TITLE
Perform some stateful Action on the Resource

### ISSUE THREAD

**Issue by alvaroperezc** [CSCI-GA-2820-SP24-001/shopcarts#41]
**As a** system user
**I need** to control my shopcart and items within it
**So that**   I can update/create/delete them
   
 ### Details and Assumptions
 * changes are made immediately and are persistent
 * users can only edit their own shopcarts and items within them
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I am in the application
 When I would like to add, delete, or edit my shopcart and/or items within it 
 Then I am able to do so in realtime
```

**Comment by whykay-01** [comment]
@alvaroperezc same for this one. We probably need to create 2 separate story lines for items and shopcarts respectively.
