### ISSUE TITLE
Add query capability to your model

### ISSUE THREAD

**Issue by alvaroperezc** [CSCI-GA-2820-SP24-001/shopcarts#42]
**As a** system admin
**I need** to be able to query my models
**So that** I am able to see what is stored or not stored in them 
   
 ### Details and Assumptions
 * Models to be queries are items and shopcarts
 * queries will display all the information displayable in them
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that I query for a column in the model created
 When I execute the action
 Then data is returned realtime as is stored in the model
```

**Comment by whykay-01** [comment]
We will have the query capability once the issues with querying shopcarts and items would be implemented. Those add-ons for the routes cannot be finished without the query capability for the model itself.
