### ISSUE TITLE
Create a .github/workflows/ci.yml file and configure GitHub Actions

### ISSUE THREAD

**Issue by vidishaholsambre** [CSCI-GA-2820-SP24-001/shopcarts#43]
**As a** developer
**I need** to create a YAML file that defines the continuous integration workflow for the project 
**So that** GitHub Actions knows what to do, when to do it, and how to do it.
   
 ### Details and Assumptions
 * File should specify that unit test cases should be run every time someone pushes to the master branch or submits a Pull Request.
 * Should run both TDD test cases and BDD test cases
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a developer is working on adding or updating the code of the platform
 When code is pushed to the master branch or a pull request is submitted
 Then the unit test cases should run every time
```

**Comment by whykay-01** [comment]
just for the reference: https://github.com/nyu-devops/lab-flask-tdd/blob/master/.github/workflows/ci.yml
