### ISSUE TITLE
External Access for Shopcart Microservice

### ISSUE THREAD

**Issue by sp7455** [CSCI-GA-2820-SP24-001/shopcarts#82]
**As a** developer
**I need** to create a secure, scalable route in OpenShift for the shopcart microservice
**So that** customers can interact with their shopping carts through our e-commerce platform's frontend, enhancing user experience.
   
 ### Details and Assumptions
- The shopcart microservice is developed with RESTful API endpoints for cart operations.
- TLS termination is set up at the route for secure HTTPS communications.
- Load balancing is considered for handling peak traffic loads effectively.
   
 ### Acceptance Criteria  
   
 ```gherkin
Given the shopcart microservice is deployed in an OpenShift pod
When I create a secure and scalable route with TLS termination for the service
Then customers can securely access and manage their shopping carts through the e-commerce platform's frontend interface
```

**Comment by whykay-01** [comment]
https://shopcarts-whykay-01-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/
