### ISSUE TITLE
update the price of the product, if price changes

### ISSUE THREAD

**Issue by sp7455** [CSCI-GA-2820-SP24-001/shopcarts#9]
**As a** user
**I need** to see the latest price for the product
**So that** I could decide whether to buy when the price changes while the product is in the shopping cart.
   
 ### Details and Assumptions
 * The price changes frequently on the ecommerce platform and the user has the product in the shopcart while the price changes
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given Shopping cart API is functional
 When the next time the user sees the cart 
 Then they see the updated price
```

**Comment by whykay-01** [comment]
bind to the PUT single item

**Comment by whykay-01** [comment]
closing the issue cause we have a duplicate issue serving the same goal
